### ISSUE TITLE
Provide versioned documentation

### ISSUE THREAD

**Issue by GabyUnalaq** [eclipse-ankaios/ank-sdk-python#29]
## Description

Currently the documentation is automatically generated for the main branch. The documentation should support multiple versions, to support users that use other versions of the SDK.

## Goals

Generate versioned documentation. The versions should be `0.5.0` after it is released and `latest` or `main` for the main documentation.

## Hints

1. The library used for generating documentation is sphinx, and for the versioned documentation, there is an extension called `sphinx-multiversion` that generated multiple documentations based on the provided version.
2. For the version selection, apparently there are 2 approaches:
   * [Lower-Left selection](https://docs.conan.io/1/index.html)
   * [Lower-Right selection](https://sphinx-versioned-docs.readthedocs.io/en/latest/)
3. The documentation is automatically generated using the [documentation](https://github.com/eclipse-ankaios/ank-sdk-python/blob/main/.github/workflows/documentation.yml) action and it uses the workflow approach.

### Summary

- **How the versioned documentation works**

- **How the GitHub workflow publish documentation works**

### Tasks

- [x] Check the documentation thoroughly (typos, readability, style issues)
- [x] Investigate how to generate versioned documentation.
- [x] Investigate how to publish versioned documentation with the GitHub workflow style.
- [x] Implement the changes.

**Comment by windsource** [comment]
If possible we should not differentiate between patch versions. So instead `0.5.0`, `0.5.1`, `0.6.0`, `0.6.1` it should only be `0.5`and `0.6`. For Ankaios we have chosen `main` rather than `latest` as latest shall be the latest release.

**Comment by GabyUnalaq** [comment]
The task was completed, issue can be closed.
