### ISSUE TITLE
Add software tests

### ISSUE THREAD

**Issue by GabyUnalaq** [eclipse-ankaios/ank-sdk-python#30]
## Description

There should be a way to automatically test the Python SDK in a real container with a working Ankaios cluster. Having this, we should be able to minimize the problems that might appear during development and corner cases that are not tested correctly in the moment. The software tests should also be mandatory to run on every PR, to be sure that the functionality of the SDK is no affected.

## Goals

Software tests are implemented and are testing at least once all of the methods of the Ankaios class that communicate with the Ankaios cluster.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Investigate a way to implement software tests
- [ ] Investigate what cases should be tested with software tests
- [ ] Make sure all tests pass
- [ ] Add them to GitHub action.
