### ISSUE TITLE
Create images for illustrating the structure and workflow

### ISSUE THREAD

**Issue by GabyUnalaq** [eclipse-ankaios/ank-sdk-python#45]
## Description

The Python SDK has documentation, and that is a good starting point for accommodating,
but having some images that show details would help in better  understanding the sdk.
For instance, there can be an image illustrating the inner structure of the sdk, a graph with
the classes and the relations between them, or the workflows of different operations:
applying a manifest, creating a workload etc.

Example from Ankaios:
https://github.com/eclipse-ankaios/ankaios/tree/main/api/doc/swdesign/drawio

## Goals

Images are created that illustrate how the SDK works.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Analize what can be illustrated.
- [ ] Find a way to programmatically create the diagrams (see example from main repo).
- [ ] Generate the images.
- [ ] Optional: Add the images to the documentation and readme.
